# fly.toml app configuration file generated for flights-ui on 2025-10-26T11:34:01-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'flights-ui'
primary_region = 'sjc'

[build]
  dockerfile = 'Dockerfile.frontend'

[env]
  VITE_API_URL = 'https://flights-api.fly.dev'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
