# fly.toml app configuration file generated for flights-api on 2025-10-26T11:29:30-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'flights-api'
primary_region = 'sjc'

[build]
  dockerfile = 'Dockerfile'

[env]
  FLIGHTS_CSV = '/app/flights.csv'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
