# Render Blueprint for Flight Finder
# This file defines both the backend and frontend services
services:
  # Backend API Service
  - type: web
    name: flights-api
    env: python
    region: oregon
    branch: main
    buildCommand: "pip install -r server/requirements.txt"
    startCommand: "cd server && uvicorn server:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLIGHTS_CSV
        sync: false
    healthCheckPath: /api/flights
  # Frontend Static Site
  - type: web
    name: flights-ui
    env: static
    branch: main
    buildCommand: "cd client && npm install && npm run build"
    staticPublishPath: ./client/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
